######## Style ########
style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
    
######## Sidebar ########
sidebar:
  menu:
    post: '[éšç¬”](/)'
    wiki: '[ä¸“æ ](/wiki/)'
    notes: '[ä¾¿ç¬º](/notes/)'
    more: '[å…³äº](/about/)'
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'

######## Footer ########
footer:
  social:
    - icon: '<img src="https://files.coolkes.com/images/gmail.svg"/>'
      url: mailto:iopanjing@gmail.com
    - icon: '<img src="https://files.coolkes.com/images/github.svg"/>'
      url: https://github.com/coolkes
    - icon: '<img src="https://static.zhihu.com/heifetz/favicon.ico"/>'
      url: https://www.zhihu.com/people/coolkes
      
  sitemap:
    'ğŸ¯ åšå®¢':
      - '[ğŸ§© åˆ†ç±»](/categories/)'
      - '[ğŸ“» æ ‡ç­¾](/tags/)'
      - '[âš™ï¸ å½’æ¡£](/archives/)'
    'ğŸ‰ ä¸“æ ':
      - '[â“ ä¸ºä»€ä¹ˆè¿™ä¹ˆè®¾è®¡](/wiki/why-design/)'
      - '[ğŸ“– è¯»ä¹¦ç¬”è®°](/wiki/read-notes/)'
    'ğŸ» ç¤¾äº¤':
      - '[ğŸ«° æœ‹å‹åœˆ](/friends)'
      - '[ğŸ“‘ ç•™è¨€æ¿](/)' 
    'ğŸ’¦ æ›´å¤š':
      - '[ğŸ‘‹ å…³äºæœ¬ç«™](/about/)'
      - '[âš”ï¸ GitHub](https://github.com/coolkes)'
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  source: '[GitHub](https://github.com/coolkes/coolkes.github.io)'
  more: 
    <hr/>
    <div align="left">
      <img src="https://su3.cn/p/imgs/beian.png" title="å¤‡æ¡ˆç®¡ç†ç³»ç»Ÿ" style="width:12px; height:12px; margin:0 5px 0 0;"> 
      <a href="http://beian.miit.gov.cn/" style="text-decoration:none;" target="_blank" title="å¤‡æ¡ˆå·">è±«ICPå¤‡2021033222-1</a>
    </div>


######## Article ########
article:
  # å¦‚æœæ²¡æœ‰æŒ‡å®šå°é¢ï¼Œæ˜¯å¦æ ¹æ® tags ä½œä¸ºå…³é”®è¯æœç´¢å°é¢å›¾ç‰‡ï¼Ÿ
  auto_cover: false # search from https://source.unsplash.com/
  # å¦‚æœæ²¡æœ‰æŒ‡å®šæ¨ªå¹…ï¼Œæ˜¯å¦æ ¹æ® tags ä½œä¸ºå…³é”®è¯æœç´¢æ¨ªå¹…å›¾ç‰‡ï¼Ÿ
  auto_banner: false # search from https://source.unsplash.com/
  # å¦‚æœæ²¡æœ‰æŒ‡å®š excerpt å’Œ descriptionï¼Œå°†è‡ªåŠ¨å–å¤šé•¿çš„å†…å®¹ä½œä¸ºæ–‡ç« æ‘˜è¦ï¼Ÿ
  auto_excerpt: 200
  # æ–‡ç« è®¸å¯åè®®
  license: #'æœ¬æ–‡é‡‡ç”¨ [ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚'
  # åˆ†äº«
  share: [wechat, weibo, email, link]